id: IA7132AB0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:29:37+00:00'
last_modified: '2022-06-07T12:13:08.896965+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90122
  title: ཁྲོ་ཆུ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    09CB:
      image_group_id: I1PD90139
      title: Volume 1 of khro chu rdzong gi sa cha'i ming btus
      total_pages: 162
      order: 1
      base_file: 09CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
